// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0Bd_8BnBkES1LM1vn4YCKPFLau61Szt4',
    appId: '1:406809548170:web:6fed44fcfe9314e1b9a473',
    messagingSenderId: '406809548170',
    projectId: 'cooking-app-68f57',
    authDomain: 'cooking-app-68f57.firebaseapp.com',
    storageBucket: 'cooking-app-68f57.appspot.com',
    measurementId: 'G-LYEYBM135Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAirW6kOCsrizEqx9wTWGDAlWnOFfsCnWc',
    appId: '1:406809548170:android:e760b82d881cd0edb9a473',
    messagingSenderId: '406809548170',
    projectId: 'cooking-app-68f57',
    storageBucket: 'cooking-app-68f57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7IXMB37o2Yab-FFoxJOhezIE36RaTiwI',
    appId: '1:406809548170:ios:cfa9d21d6704189db9a473',
    messagingSenderId: '406809548170',
    projectId: 'cooking-app-68f57',
    storageBucket: 'cooking-app-68f57.appspot.com',
    iosBundleId: 'com.example.cookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7IXMB37o2Yab-FFoxJOhezIE36RaTiwI',
    appId: '1:406809548170:ios:cfa9d21d6704189db9a473',
    messagingSenderId: '406809548170',
    projectId: 'cooking-app-68f57',
    storageBucket: 'cooking-app-68f57.appspot.com',
    iosBundleId: 'com.example.cookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0Bd_8BnBkES1LM1vn4YCKPFLau61Szt4',
    appId: '1:406809548170:web:80067a5318222330b9a473',
    messagingSenderId: '406809548170',
    projectId: 'cooking-app-68f57',
    authDomain: 'cooking-app-68f57.firebaseapp.com',
    storageBucket: 'cooking-app-68f57.appspot.com',
    measurementId: 'G-L6QB96RSQ4',
  );

}