// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfZIbkXaTTRIKhhQ2qClr2U-EKHqWuzh8',
    appId: '1:396768825712:web:4e66708e69f0a124aa7fb5',
    messagingSenderId: '396768825712',
    projectId: 'cook-with-ai-fb389',
    authDomain: 'cook-with-ai-fb389.firebaseapp.com',
    storageBucket: 'cook-with-ai-fb389.appspot.com',
    measurementId: 'G-YR6HC3PLFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH6CsN9m0Y88Dm7ZYIjp40jLOvRYExbOQ',
    appId: '1:396768825712:android:635bcb362cf2514caa7fb5',
    messagingSenderId: '396768825712',
    projectId: 'cook-with-ai-fb389',
    storageBucket: 'cook-with-ai-fb389.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZDhYxrfMbYU0kJ735AN402r-hB0_tW4w',
    appId: '1:396768825712:ios:2a693324cf593800aa7fb5',
    messagingSenderId: '396768825712',
    projectId: 'cook-with-ai-fb389',
    storageBucket: 'cook-with-ai-fb389.appspot.com',
    iosBundleId: 'com.example.cookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZDhYxrfMbYU0kJ735AN402r-hB0_tW4w',
    appId: '1:396768825712:ios:2a693324cf593800aa7fb5',
    messagingSenderId: '396768825712',
    projectId: 'cook-with-ai-fb389',
    storageBucket: 'cook-with-ai-fb389.appspot.com',
    iosBundleId: 'com.example.cookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfZIbkXaTTRIKhhQ2qClr2U-EKHqWuzh8',
    appId: '1:396768825712:web:4e66708e69f0a124aa7fb5',
    messagingSenderId: '396768825712',
    projectId: 'cook-with-ai-fb389',
    authDomain: 'cook-with-ai-fb389.firebaseapp.com',
    storageBucket: 'cook-with-ai-fb389.appspot.com',
    measurementId: 'G-YR6HC3PLFF',
  );

}